variable env {}
variable app_name {}
variable image {}
variable region {}
variable loggroup {}
variable execution_role_arn {}
variable security_id {}
variable subnet1 {}
variable subnet2 {}
variable target_group_arn {}